ENT.Base 			= "obj_vj_spawner_base"
ENT.Type 			= "anim"
ENT.PrintName 		= "Flood Swarm Form Flock"
ENT.Author 			= "DrVrej"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Halo Wars Resurgence"
ENT.Spawnable		= false
ENT.AdminSpawnable	= false